trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    goals: 'compile org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom'
# Pull the sast-scan image from the container registry. Feel free to cache it locally within acr, ecr or gcr to
# improve performance and security
- script: docker pull quay.io/appthreat/sast-scan
  displayName: "Download sast-scan"
- script: |
    docker run -e "WORKSPACE=https://github.com/AppThreat/WebGoat/blob/$(Build.SourceVersion)" \
      -e "REPOSITORY_URL=$(Build.Repository.Uri)" \
      -e "COMMIT_SHA=$(Build.SourceVersion)" \
      -e "GITHUB_TOKEN=$(GITHUB_TOKEN)" \
      -e "BRANCH=$(Build.SourceBranch)" \
      -v $(Build.SourcesDirectory):/app \
      -v $(Build.ArtifactStagingDirectory):/reports \
      quay.io/appthreat/sast-scan scan --src /app \
      --out_dir /reports/CodeAnalysisLogs
  displayName: "AppThreat SAST and Dep scan"
  continueOnError: "true"
# To integrate with the SARIF Azure DevOps Extension it is necessary to publish the CodeAnalysisLogs folder
# as an artifact with the same name
- task: PublishBuildArtifacts@1
  displayName: "Publish analysis logs"
  inputs:
    PathtoPublish: "$(Build.ArtifactStagingDirectory)/CodeAnalysisLogs"
    ArtifactName: "CodeAnalysisLogs"
    publishLocation: "Container"
